version: '3.3'
services:
  mysqldb:
    env_file:
      - .env
    image: mysql:5.7
    container_name: devCrmMysql
    ports:
      - 3364:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_passwd}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_passwd}
      MYSQL_DATABASE: ${mysql_db}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysqldb:mysql
    container_name: devCrmMyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always

  webserver:
    container_name: devCrmServer
    image: crm-webapp:1.0.0
    build:
      context: .
      dockerfile: dockerfiles/project1/Dockerfile
      args:
        VERSION: ${espo}
    ports:
      - 8088:80
    volumes:
      - ./espocrm:/crm/espocrm
      - ./projects/project1/application:/crm/espocrm/custom
      - ./projects/project1/client/custom:/crm/espocrm/client/custom
      - ./addons/PM-Extension/files/application/Espo/Modules/PM:/crm/espocrm/application/Espo/Modules/PM
      # - ./addons/PM-Extension/files/client/modules/pm:/crm/espocrm/client/modules/pm
      - ./tests:/crm/espocrm/tests
      - ./etc/nginx/conf.d/espocrm.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      DB_HOST: ${mysql_host}
      DB_USER: ${mysql_user}
      DB_PASSWORD: ${mysql_passwd}
      DB_NAME: ${mysql_db}
      DB_DRIVER: mysqldb:mysql
    links:
      - mysqldb:mysql
    command: "nginx -g 'daemon off;'"

volumes:
  mysql-data:
