version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: espocrm

  phpfpm:
    image: php-source:1.0
    ports:
      - 9000:9000
    volumes:
      - ./php7/espocrm:/var/www/html/espocrm
    environment:
      DB_HOST: mysqldb
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: espocrm
      DB_DRIVER: mysqldb:mysql
    links:
      - mysqldb:mysql

  webserver:
    image: nginx:alpine
    links:
      - phpfpm
    ports:
      - 80:80
    volumes:
      - ./php7/espocrm:/var/www/html/espocrm
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html

