version: '3.3'
services:
  web:
    image: nginx:alpine
    ports:
      - 8000:8000
    environment:
      - NGINX_HOST=localhost
    volumes:
      - ./espo-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./espo-nginx/nginx.conf:/etc/nginx/sites-available/default
      - ./espo-nginx/nginx.conf:/etc/nginx/sites-enabled/default
    links:
      - phpfpm
    restart: always
    depends_on:
      - phpfpm
  phpfpm:
    image: php7.1:alpine-espo
    restart: always
    ports:
      - 9000:9000
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ".env"
    links:
      - mysql
    ports:
      - 8183:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      PMA_ARBITRARY: 1
    restart: always