version: '3.3'
services:
  web:
    image: espocrm:v2
    ports:
      - 8000:8000
    environment:
      - NGINX_HOST=localhost
    volumes:
      - "./dockerised-espo/espocrm:/usr/share/nginx/html"
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/app.conf > /etc/nginx/conf.d/app.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php

  php:
    image: php:7.1-fpm
    restart: always
    volumes:
      - "./dockerised-espo/espocrm:/var/www/html"

  # mysqldb:
  #   image: mysql:${MYSQL_VERSION}
  #   container_name: ${MYSQL_HOST}
  #   restart: always
  #   env_file:
  #     - ".env"
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #   ports:
  #     - "3364:3306"
  #   volumes:
  #     - "./data/db/mysql:/var/lib/mysql"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
